### ISSUE TITLE
Please help with client issue and npm install on main folder

### ISSUE THREAD

**Issue by MNoman111** [amazingandyyy/mern#20]
First of all thanks for the boilerplate. Im facing 2 issues one with npm install on main folder. Im getting the following error:
> @amazingandyyy/git-hooks@0.1.0 install /Users/noman/mern/mern/node_modules/@amazingandyyy/git-hooks
> node install

internal/fs/utils.js:759
    throw new ERR_INVALID_ARG_TYPE('mode', 'integer', mode);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received type string ('utf-8')
    at Object.copyFileSync (fs.js:1989:10)
    at installHook (/Users/noman/mern/mern/node_modules/@amazingandyyy/git-hooks/install.js:29:10)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/noman/mern/mern/node_modules/@amazingandyyy/git-hooks/install.js:35:7)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @amazingandyyy/git-hooks@0.1.0 install: `node install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @amazingandyyy/git-hooks@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/noman/.npm/_logs/2021-02-05T04_55_14_942Z-debug.log

and another Im facing is that whenever I try to run npm run dev on client folder the browser keeps loading and just won't show anything

node version: v14.15.4
npm version: 6.14.10

**Comment by KenethSandoval** [comment]
I think it is because of node version, try to use version 10

**Comment by amazingandyyy** [comment]
@MNoman111  does it get resolved?
